### ISSUE TITLE
Css file is missing

### ISSUE THREAD

**Issue by tilakmali24** [kontent-ai/sample-app-net#138]
### Brief bug description

site.css file is missing.

**Comment by Simply007** [comment]
We need to make more explicit, that `npm run build` will produce the CSS file in the README: https://github.com/kontent-ai/sample-app-net#getting-started. So if you follow the Getting started section, you should end up with CSS file being generated.

Note: It is also part of the CI pipeline - https://github.com/kontent-ai/sample-app-net/blob/master/.github/workflows/integrate.yml#L28
